language: python
python: 3.4
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - ssh github.com
  - psql -c 'create database ci_test_test;' -U postgres
script: "python manage.py runtests"
